main: me.prisonranksx.PrisonRanksX
version: 2.5.8
name: PrisonRanksX
author: TheGaming999 aka Al3rb
softdepend: [Vault,PlaceholderAPI,MVdWPlaceholderAPI,HolographicDisplays,ActionUtil,PermissionsEX,GroupManager,LuckPerms]